MODEL:
  META_ARCHITECTURE: "human_centric_spatial_branch"
  WEIGHT: "pretrained_model/e2e_faster_rcnn_R_50_FPN_1x.pth" # only use backbone here
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("vcoco_train",)
  VAL: ("vcoco_val",)
  TEST: ("vcoco_test",)
  NUM_CLASSES: 29
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (180000, 800000)
  MAX_ITER: 1000000
OUTPUT_DIR: "output/VCOCO_sp_human_only"
TB_DIR: "output/VCOCO_sp_human_only/tensorboard"
